- name: Config pmm server via pmm-admin
  shell: "pmm-admin config --force --server-insecure-tls --server-url=https://admin:admin@ansible:{{ pmm_port }}"

- name: Add mysql via pmm-admin for mgr&slave_monitor&mysql group
  shell: "pmm-admin add mysql --query-source=slowlog --username=pmm --password='{{ pmm_password }}' --host=127.0.0.1 --port={{ mysql_port }}"
  when: config_mysql

- name: Add proxysql via pmm-admin for proxysql group
  shell: "{{ item }}"
  with_items:
    - "pmm-admin add proxysql --username=admin --password='{{ admin_login_password }}' --host=127.0.0.1 --port=6032"
  when: config_proxysql

- name: Add mongodb metric via pmm-admin
  shell: "pmm-admin add mongodb --username=root --password=\'{{ root_password }}\' --environment={{ env }} --replication-set=\'{{ replsetname }}\'"
  when: config_mongodb

- name: Add mongos metric via pmm-admin
  shell: "pmm-admin add mongodb --username=root --password=\'{{ root_password }}\' --environment={{ env }} --cluster=\'mongodb_shard\'"
  when: inventory_hostname_short in groups.mongos and config_mongodb

- name: Add mongoc metric via pmm-admin
  shell: "pmm-admin add mongodb --username=root --password=\'{{ root_password }}\' --environment={{ env }} --cluster=\'mongodb_shard\' --replication-set=replconf"
  when: inventory_hostname_short in groups.mongoconf and config_mongodb

# - name: Add mongoshard0 metric via pmm-admin
#   shell: "pmm-admin add mongodb --username=pmm --password=\'{{ root_password }}\' --environment={{ env }} --cluster=mongodb_shard --replication-set=shard0"
#   when: groups.mongoshard.index(inventory_hostname) >= 0 and groups.mongoshard.index(inventory_hostname) < 3 and config_mongodb

# - name: Add mongoshard1 metric via pmm-admin
#   shell: "pmm-admin add mongodb --username=pmm --password=\'{{ root_password }}\' --environment={{ env }} --cluster=mongodb_shard --replication-set=shard1"
#   when: groups.mongoshard.index(inventory_hostname) > 2 and groups.mongoshard.index(inventory_hostname) < 6 and config_mongodb

# - name: Add mongoshard2 metric via pmm-admin
#   shell: "pmm-admin add mongodb --username=pmm --password=\'{{ root_password }}\' --environment={{ env }} --cluster=mongodb_shard --replication-set=shard2"
#   when: groups.mongoshard.index(inventory_hostname) > 5 and config_mongodb