- name: Config pmm server via pmm-admin
  shell: "pmm-admin config --force --server-insecure-tls --server-url=https://admin:admin@{{ pmm_hostname }}:{{ pmm_port }}"

- name: Add proxysql via pmm-admin for proxysql group
  shell: "pmm-admin add proxysql --username=admin --password='{{ admin_login_password }}' --host=127.0.0.1 --port=6032"