- name: Config pmm server via pmm-admin
  shell: "pmm-admin config --force --server-insecure-tls --server-url=https://admin:{{ pmm_admin_password }}@ansible:{{ pmm_port }}"

- name: Add mongodb metric via pmm-admin
  shell: "pmm-admin add mongodb --username=root --password=\'{{ root_password }}\' --environment={{ env }} --replication-set=\'{{ replsetname }}\'"