- name: Config pmm server via pmm-admin
  shell: "pmm-admin config --force --server-insecure-tls --server-url=https://admin:admin@ansible:{{ pmm_port }}"

- name: Add mysql via pmm-admin for mgr&slave_monitor&mysql group
  shell: "pmm-admin add mysql --query-source=slowlog --username=pmm --password='{{ pmm_password }}' --host=127.0.0.1 --port={{ mysql_port }}"
  when: >
          ( ansible_hostname in groups.mgr_pro1 ) or
          ( ansible_hostname in groups.slave_monitor )

- name: Add proxysql via pmm-admin for proxysql group
  shell: "{{ item }}"
  with_items:
    - "pmm-admin add proxysql --username=admin --password='{{ admin_login_password }}' --host=127.0.0.1 --port=6032"
  when: >
          ( ansible_hostname in groups.proxysql_pro1 )

- name: Add mongos metric via pmm-admin
  shell: "pmm-admin add mongodb --username=root --password=\'{{ root_password }}\' --environment={{ env }} --cluster=\'mongodb_shard\'"
  when: inventory_hostname_short in groups.mongos

- name: Add mongoc metric via pmm-admin
  shell: "pmm-admin add mongodb --username=root --password=\'{{ root_password }}\' --environment={{ env }} --cluster=\'mongodb_shard\' --replication-set=replconf"
  when: inventory_hostname_short in groups.mongoconf

- name: Add mongoshard0 metric via pmm-admin
  shell: "pmm-admin add mongodb --username=pmm --password=\'{{ root_password }}\' --environment={{ env }} --cluster=mongodb_shard --replication-set=shard0"
  when: groups.mongoshard.index(inventory_hostname) >= 0 and groups.mongoshard.index(inventory_hostname) < 3

- name: Add mongoshard1 metric via pmm-admin
  shell: "pmm-admin add mongodb --username=pmm --password=\'{{ root_password }}\' --environment={{ env }} --cluster=mongodb_shard --replication-set=shard1"
  when: groups.mongoshard.index(inventory_hostname) > 2 and groups.mongoshard.index(inventory_hostname) < 6

- name: Add mongoshard2 metric via pmm-admin
  shell: "pmm-admin add mongodb --username=pmm --password=\'{{ root_password }}\' --environment={{ env }} --cluster=mongodb_shard --replication-set=shard2"
  when: groups.mongoshard.index(inventory_hostname) > 5

- name: Add mongodb metric via pmm-admin
  shell: "pmm-admin add mongodb --username=root --password=\'{{ root_password }}\' --environment={{ env }} --replication-set=\'{{ replsetname }}\'"
  when: inventory_hostname_short in groups.mongoreplset