- name: Backup the python and the pip
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '/usr/bin/python', dest: '/usr/bin/python.bak' }
    - { src: '/usr/bin/pip', dest: '/usr/bin/pip.bak' }

- name: Create a symbolic link
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '/usr/bin/python3', dest: '/usr/bin/python' }
    - { src: '/usr/bin/pip3', dest: '/usr/bin/pip' }

- name: Modify the yum related
  replace:
    path: "{{ item }}"
    regexp: '#!/usr/bin/python'
    replace: '#!/usr/bin/python2'
  with_items:
    - { '/usr/bin/yum' }
    - { '/usr/libexec/urlgrabber-ext-down' }