- name: Install xfsprogs
  yum:
    name: [xfsprogs, expect]
    state: latest

#- name: Create a symbolic link for pip
#  file:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    state: link
#    owner: root
#    group: root
#    mode: 0755
#    force: 'yes'
#  with_items:
#    - { src: '/usr/bin/pip3', dest: '/usr/bin/pip' }

#- name: Upgrade pip
#  pip:
#    name: pip
#    state: latest
#    executable: pip3.6

#- name: Create the new disk partition
#  expect:
#    command: "fdisk {{ fdisk_src }}"
#    responses:
#      (?i)): "n"
#      (?i)): "\r"
#      (?i)): "\r"
#      (?i)): "\r"
#      (?i)): "\r"
#      (?i)): "w"
#    echo: yes

- name: Rendering format_disk.sh
  template:
    src: format_disk.sh.j2
    dest: /tmp/format_disk.sh
    owner: root
    group: root
    mode: 0774
  when: not whether_size_up_2T

- name: Create the new disk partition
  shell: "/usr/bin/expect /tmp/format_disk.sh"
  when: not whether_size_up_2T

- name: Create a new primary partition by parted
  parted:
    device: "{{ fdisk_src }}"
    label: gpt
    number: 1
    state: present
    part_start: 1%
    part_end: 100%
  when: whether_size_up_2T

# - name: Format the new disk partition
#   shell: "mkfs.xfs -f {{ fstab_src }}"

- name: Format the new disk partition
  filesystem:
    fstype: xfs
    dev: "{{ fstab_src }}"
    force: yes

- name: Mount file path for data directory
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: xfs
    opts: defaults,noatime,nobarrier
    dump: 0
    passno: 0
    state: mounted
#If mounted, the device will be actively mounted and appropriately configured in fstab. If the mount point is not present, the mount point will be created.