- name: Install xfsprogs
  yum:
    name: [xfsprogs, epel-release, python-pip, python2-pip.noarch, expect]
    state: latest

#- name: Create a symbolic link for pip
#  file:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    state: link
#    owner: root
#    group: root
#    mode: 0755
#    force: 'yes'
#  with_items:
#    - { src: '/usr/bin/pip3', dest: '/usr/bin/pip' }

#- name: Upgrade pip
#  pip:
#    name: pip
#    state: latest
#    executable: pip3.6

- name: Install pexpect
  pip:
    name: pexpect
    state: latest

#- name: Create the new disk partition
#  expect:
#    command: "fdisk {{ fdisk_src }}"
#    responses:
#      (?i)): "n"
#      (?i)): "\r"
#      (?i)): "\r"
#      (?i)): "\r"
#      (?i)): "\r"
#      (?i)): "w"
#    echo: yes

- name: Rendering format_disk.sh
  template:
    src: format_disk.sh.j2
    dest: /tmp/format_disk.sh
    owner: root
    group: root
    mode: 0774

- name: Create the new disk partition
  shell: "/usr/bin/expect /tmp/format_disk.sh"

- name: Format the new disk partition
  shell: "mkfs.xfs -f {{ fstab_src }}"

- name: Remount file path for data directory
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: xfs
    opts: defaults,noatime,nobarrier
    dump: 0
    passno: 0
    state: mounted
#If mounted, the device will be actively mounted and appropriately configured in fstab. If the mount point is not present, the mount point will be created.