- name: Stop docker server
  systemd:
    name: docker
    state: stopped
  when: docker_re_install

- name: Uninstall docker
  yum:
   name: docker
   state: absent
  when: docker_re_install

- name: Remove docker directory
  file:
    path: /var/lib/docker
    state: absent
  when: docker_re_install

- name: Install and start pmm server
  shell: "curl -fsSL https://www.percona.com/get/pmm | /bin/bash"

- name: Enable docker server
  systemd:
    name: docker
    state: started
    enabled: yes
