---
# tasks file for dba_ray.ansible
- include: initial_hosts.yml
  when: is_initial_hosts | default(False)

- include: format_disk.yml
  when: is_format_disk | default(False)

- include: system_check.yml
  when: is_system_check | default(False)

- include: initial_hosts_file.yml
  when: is_initial_hosts_file | default(False)

- include: upgrade_python.yml
  when: is_python | default(False)

- include: download_roles_packages.yml
  when: is_download_roles_packages | default(False)

- include: install_pmm_server.yml
  when: install_pmm_server | default(False)

- include: install_percona_tools.yml
  when: install_percona_tools | default(False)

- include: password.yml
  when: >
        (is_ansible_tower | default(False)) or 
        (mysql_config_editor | default(False)) or
        (config_mysql | default(False)) or
        (config_proxysql | default(False)) or
        (config_mongoreplset | default(False)) or
        (config_mongocluster | default(False)) or
        (config_mongocluster_pro | default(False))

- include: install_ansible_tower.yml
  when: is_ansible_tower | default(False)

- include: config_pmm_mysql.yml
  when: config_mysql | default(False)

- include: config_pmm_proxysql.yml
  when: config_proxysql | default(False)

- include: config_pmm_mongoreplset.yml
  when: config_mongoreplset | default(False)

- include: config_pmm_mongocluster.yml
  when: config_mongocluster | default(False)

- include: config_pmm_mongocluster_pro.yml
  when: config_mongocluster_pro | default(False)

- include: mysql_config_editor.yml
  when: mysql_config_editor | default(False)