---
# tasks file for dba_ray.ansible
- include: format_disk.yml
  when: is_format_disk | default(False)
  run_once: true

- include: password.yml
  when: is_ansible_tower | default(False)

- include: system_check.yml
  run_once: true

- include: enable_pyhon3.yml
  when: is_python3 | default(False)

- include: install_ansible_tower.yml
  when: is_ansible_tower | default(False)

- include: download_roles_packages.yml
  when: is_download_roles_packages | default(False)