- name: Install mysql resource
  yum:
    name: "{{ remote_repo }}"
    state: present

- name: Copy the mysql-community.repo
  copy: src=mysql-community.repo dest=/etc/yum.repos.d/mysql-community.repo

- name: Install mysql client
  yum:
    name: mysql-community-client.x86_64
    state: present
  register: result
  retries: 3
  until: result is succeeded

- name: Install pexpect
  pip:
    name: pexpect
    state: latest

- name: Rendering mysql_config_editor.sh.j2
  template:
    src: mysql_config_editor.sh.j2
    dest: /tmp/mysql_config_editor.sh
    owner: root
    group: root
    mode: 0774

- name: Case sensitive password string match for logining mysql
  expect:
    command: "/usr/bin/mysql_config_editor set --login-path={{ hostvars[item]['inventory_hostname_short'] }}_root --host={{ hostvars[item]['inventory_hostname_short'] }} -P {{ mysql_port }} --user=root --password"
    responses:
      (?i)password: "{{ root_password }}"
      (?i)Continue: y
    echo: yes
  with_items:
    - "{{ groups.mgr_pro1 }}"
    - "{{ groups.slave_monitor }}"
  no_log: True

- name: Case sensitive password string match for logining proxysql
  expect:
    command: "/usr/bin/mysql_config_editor set --login-path={{ hostvars[item]['inventory_hostname_short'] }}_repl --host={{ hostvars[item]['inventory_hostname_short'] }} -P 6032 --user=repl --password"
    responses:
      (?i)password: "{{ mysql_monitor_password }}"
      (?i)Continue: y
    echo: yes
  with_items:
    - "{{ groups.proxysql_pro1 }}"
  no_log: True

#- name: Config case sensitive password string match for logining proxysql or mysql
#  shell: "sh -x /tmp/mysql_config_editor.sh"

#- name: Remove mysql_config_editor.sh.j2
#  file:
#    path: "/tmp/mysql_config_editor.sh"
#    state: absent