- name: Stop firewalld
  service: name=firewalld state=stopped enabled=no

- name: Disable selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Comment out swap info
  shell: "sed -i '/swap/s/^/##/' /etc/fstab"

- name: Uninstall mariadb and percona server
  yum:
    name: ["mariadb*", "Percona-XtraDB-Cluster*", "Percona-Server*"]
    state: absent

- name: Disable kernel hugepage and adjust aio
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled;echo never > /sys/kernel/mm/transparent_hugepage/defrag;echo 1048576 > /proc/sys/fs/aio-max-nr"

- name: Disable swap,expand tcp connection parameter,modify memory strategy and enable network forward
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.conf
  with_items:
    - { name: 'net.core.somaxconn', value: 8096 }
    - { name: 'vm.overcommit_memory', value: 1 }
    - { name: 'vm.swappiness', value: 0 }
    - { name: 'net.ipv4.ip_forward', value: 1 }

- name: Add or modify all nofile limits for wildcard domain
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: nofile
    value: 65535
  with_items:
    - hard
    - soft

- name: Disable file system atime,barrier for root directory
  mount:
    path: /
    src: "{{ ansible_cmdline.root }}"
    fstype: ext4
    opts: defaults,noatime,nobarrier
    state: mounted
    backup: yes
    dump: '1'
    passno: '1'

- name: Remount file path for root directory
  mount:
    path: /
    src: "{{ ansible_cmdline.root }}"
    fstype: ext4
    opts: defaults,noatime,nobarrier
    state: remounted

- name: Disable file system atime,barrier for data directory
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: xfs
    opts: defaults,noatime,nobarrier
    state: mounted
    backup: yes
  when: whether_remount_data_disk

- name: Remount file path for data directory
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: xfs
    opts: defaults,noatime,nobarrier
    state: remounted
  when: whether_remount_data_disk