- name: Backup the python and the pip
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '/usr/bin/python', dest: '/usr/bin/python.bak' }
    - { src: '/usr/bin/pip', dest: '/usr/bin/pip.bak' }

# - name: Modify the yum related
#   replace:
#     path: "{{ item }}"
#     regexp: '#!/usr/bin/python'
#     replace: '#!/usr/bin/python2'
#   with_items:
#     - '/usr/bin/yum'
#     - '/usr/libexec/urlgrabber-ext-down'

- name: Copy pip compressed package
  copy:
    src: pip-20.2.4.tar.gz
    dest: "{{ package_dir }}"

- name: Uncompress pip package
  unarchive:
    src: "{{ package_dir }}/pip-20.2.4.tar.gz"
    dest: "{{ package_dir }}"
    remote_src: yes

- name: Setup pip package
  shell: "python {{ package_dir }}/pip-20.2.4/setup.py install"

# - name: Create a symbolic link
#   file:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     state: link
#   with_items:
#     - { src: '/usr/bin/python', dest: '/usr/bin/python2.7.9' }
#     - { src: '/usr/bin/pip3.6', dest: '/usr/bin/pip' }